### ISSUE TITLE
Needs a colorblind mode

### ISSUE THREAD

**Issue by sophiebits** [jbowens/codenames#10]
The current styles are not sufficient for a colorblind spymaster to tell the difference between colors. I used these styles successfully with a friend:

```
.cell {
  width: 130px;
  height: 90px;
  box-sizing: border-box;
}
.codemaster .red.hidden-word,
.red.revealed {
  outline: 2px dashed #d13030;
  border: 1px solid white;
}
.codemaster .blue.hidden-word {
  outline: 2px solid #4183cc;
  border: 1px solid white;
}
.blue.revealed {
  outline: 2px solid #4183cc;
  border: 1px solid white;
}
.revealed .word {
  text-decoration: underline;
}
```

![screenshot of proposed styles](https://user-images.githubusercontent.com/6820/42193522-b60b8726-7e23-11e8-9162-13c38b353919.png)

I don't have time right now to submit a PR for this but hopefully this is a useful starting point. Remaining work:

* add a toggle to enable/disable this mode
* add a legend describing the styles
* add labels to the score too

**Comment by jbowens** [comment]
Good call! I'll try to find time for this soon
