### ISSUE TITLE
Shuffle deck (only cards that haven't been used)

### ISSUE THREAD

**Issue by sheriffderek** [jbowens/codenames#106]
This is super great. Very fun. I love it. I'll keep buying coffees - so / I'll just say that once. : )

We just played 4 games and many of the same cards came up every time. Maybe there can be yates shuffle type thing that isn't just rand - and pulls from the array until it's gone / excluding the used cards. Is that how the game works IRL, right?

**Comment by jbowens** [comment]
Hmm, that _should_ be how it already works. (See #58). It's possible there was a regression.

**Comment by jbowens** [comment]
Added 6d41570 and everything seems correct at least in the Game mechanics. I also haven't been able to reproduce this end-to-end. Maybe the game you joined already existed and didn't have a fresh deck?

**Comment by sheriffderek** [comment]
The link that came to me was: https://www.horsepaste.com/broccamol%C3%A9

and - could be from before April 1st. When I create a new URL / looking through 10 rounds or so - it seems to all be shuffled properly!

So - I think it's all good!

Is there any way to retroactively address it? Why would the old URL keep the old functions? Is it cached or service workers or something?
