### ISSUE TITLE
Add outlines / visual differentiation + outlines for cards / blue & red - 

### ISSUE THREAD

**Issue by sheriffderek** [jbowens/codenames#107]
In low light - many of us found it hard to differentiate blue and red cards as spymasters.

![Screen Shot 2020-05-09 at 12 13 15 AM](https://user-images.githubusercontent.com/2066617/81466903-e6fb5700-9189-11ea-9212-04efb9ce7427.png)
Maybe just colored outlines would be enough - or something like this.

Also / just a side note... maybe the cards are orange and green - or something less "red/blue" ? (maybe it's just me in the U.S. - but I'm sick of that... haha)

**Comment by jbowens** [comment]
Have you tried the colorblind mode? The gear at the bottom will open a settings page. The color blind mode adds patterned outlines.

**Comment by sheriffderek** [comment]
Awesome. I'm not color blind - but I'll be keeping this setting on! : )

**Comment by jamre** [comment]
Two of our spymasters were complaining about this tonight as well. Both were using color blind mode. Neither are color blind, but one does have a visual impairment. It was also hard for that person to even find the gear since it's almost invisible on a white background.

I'll try changing their border thickness to 4px next time to see if that helps.

**Comment by jamre** [comment]
Using the Chrome DevTools, we changed the outline to 4px and changed the font size to 2vw and that was much better for her.

**Comment by jbowens** [comment]
> It was also hard for that person to even find the gear since it's almost invisible on a white background.

Good call. The gear should be more visible.

> Using the Chrome DevTools, we changed the outline to 4px and changed the font size to 2vw and that was much better for her.

Good to know. I'll look at committing those changes this week.
