### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by carrierfry** [jbowens/codenames#11]
Would be great to add multi-language support to the game. Would volunteer to add german version of word list.

**Comment by fdenzer** [comment]
Would volunteer to bug-hunt on the / playtest the german version.

> Also, would play IRL in Mainz, Germany.

**Comment by jbowens** [comment]
@007checker now that #15 has landed, this would be a lot easier to implement. Do you have a word list?

**Comment by empz** [comment]
@jbowens 

I'm interested in adding a spanish word set. I already have 400 words from the orignal game.

Would you accept a PR to add this? If so, can you point me exactly where should I add this word set?

**Comment by jbowens** [comment]
Hi @eparizzi, for sure! The more languages the merrier. New languages can be added as a new key in the [frontend/words.json](https://github.com/jbowens/codenames/blob/master/frontend/words.json). Here are a few example PRs adding other languages: #27, #29, #38

**Comment by jbowens** [comment]
I'm going to close this issue because multiple issues are now supported, but feel free to comment here if you have more questions about this.
