### ISSUE TITLE
Enforce timer not working

### ISSUE THREAD

**Issue by SayantaBhar** [jbowens/codenames#113]
Enforce timer stops working after playing few rounds of the game or maybe after taking certain actions.

**Comment by SayantaBhar** [comment]
Created this with enforced timer on:
https://www.horsepaste.com/we-will-rock-you
Worked initially but now its not working.

**Comment by SayantaBhar** [comment]
This enforce timer works for the very first game only. For subsequent games its not enforcing.

**Comment by jbowens** [comment]
Thanks for the bug report. I haven't had time to take a look yet, but I'll try to get to it this week.
