### ISSUE TITLE
Have a colorblind option

### ISSUE THREAD

**Issue by pkaiserui** [jbowens/codenames#114]
Your site is great thank you! One of my friends is colorblind and it would be great if the colors could change to have more of a difference for color blind people.

Thanks!

**Comment by jbowens** [comment]
@pkaiserui have you seen the color blind toggle in the settings? If you click the gear icon at the bottom of the game, a settings pane will pop up. There’s a toggle for a colorblind mode that adds dashed and solid outlines so that colorblind individuals can differentiate.
