### ISSUE TITLE
Etymology of name?

### ISSUE THREAD

**Issue by benesch** [jbowens/codenames#115]
Hi @jbowens, thanks very much for a great app. I'm dying to know, though: what is the etymology of "horse paste"?

**Comment by jbowens** [comment]
Oops, sorry for the delay here!

So "horse" and "paste" are both words in the original word set. A long time ago, I played a game with some friends in which someone connected those two words with the clue "glue." When I was registering a domain name, I wanted something that sounded memorable and I thought of that clue. ¯\\_(ツ)\_/¯

**Comment by benesch** [comment]
Hah, no worries at all and thanks for the explainer! You've settled some bets for me.
