### ISSUE TITLE
Answers visible to all players from standard view

### ISSUE THREAD

**Issue by ReversingWithMe** [jbowens/codenames#122]
![image](https://user-images.githubusercontent.com/22553347/88484077-4e26dd00-cf29-11ea-848b-224e2c5a0925.png)

From developer view, the type of cell, before it is toggled, is visible to all players.

**Comment by jbowens** [comment]
This is deliberate. Any player can also toggle into spymaster mode. The game assumes players aren't malicious.

**Comment by greenbigfrog** [comment]
Difference is, changing to spymaster is visible to others, looking at the source is not.

**Comment by jbowens** [comment]
> Difference is, changing to spymaster is visible to others, looking at the source is not.

No, it's not. There is presently no indication to other users that someone has switched to spymaster view.

**Comment by greenbigfrog** [comment]
> > Difference is, changing to spymaster is visible to others, looking at the source is not.
> 
> No, it's not. There is presently no indication to other users that someone has switched to spymaster view.

My bad
