### ISSUE TITLE
Prettier config/set up

### ISSUE THREAD

**Issue by orteth01** [jbowens/codenames#127]
I noticed that there is a `.prettierrc` file in the frontend folder, but i don't see prettier as a dev dependency. Is it actually set up to run at all? if not, can I make a PR to
1. add it as a dev dep
2. run it on all the frontend files
3. potentially add a pre-commit hook to format staged files to catch if any contributors make changes but do not run prettier

lmk what you think

**Comment by jbowens** [comment]
hey @orteth01, yeah, that sounds great! I think prettier was run once across the codebase in #23, but I agree it should be added as a dev dependency and ideally enforced by CI or a pre-commit hook.
