### ISSUE TITLE
Docker Issues/questions

### ISSUE THREAD

**Issue by jrbarronumd** [jbowens/codenames#130]
Thanks a bunch for all the work you've done on this!

I just installed the game via Docker and it appears everything is working.  I did have 2 questions:

  1.  I notice the horsepaste site looks a bit different on the setup screen (mostly words/language selection).  I cloned the repo and built from the dockerfile in the repo with no other steps, so is the horsepaste site running from a different repo, or is there some other reason my interface seems off?
  2.  Is there a file location to persist via a docker volume so that game progress will be saved independent of the container?

**Comment by jrbarronumd** [comment]
Disregard issue number 1.  I rebuilt the image and it fixed the issue.  Didn't do anything different, so I have no idea what happened.  I'll leave that visible in case anyone else has the same problem - delete the image and rebuild.

I am still interested in what directory to persist via volume so saved games aren't lost when I update the container or image.

**Comment by jbowens** [comment]
Hey @jrbarronumd, the process will create a `db` directory in the current working directory or use the path provided via the `PEBBLE_DIR` environment variable if set:
https://github.com/jbowens/codenames/blob/2e4fb48bfb639f240e2549bb5ff049533ca9b7a5/cmd/codenames/main.go#L41-L44

I run the process from within the `$GOPATH/src/github.com/jbowens/codenames` directory, so `$GOPATH/src/github.com/jbowens/codneames/db` is where game data is persisted.

**Comment by jrbarronumd** [comment]
Perfect, thanks!  

So for completion of this issue, I have added the following to my docker-compose.yml:

    volumes:
      - {host_volume}:/app/db

That seems to do the trick.  Thanks again for sharing this work!
