### ISSUE TITLE
Give spymaster board a password to make cheating harder

### ISSUE THREAD

**Issue by dannydarvish** [jbowens/codenames#14]
Or a separate randomized URL.

**Comment by jbowens** [comment]
I'm curious how you're using the app?

I originally anticipated it being used in the same room with people you trust. In that setting, convenience of switching spymasters is more important than preventing cheating.

**Comment by dannydarvish** [comment]
I am using it online with friends over a chatting app (Discord).

**Comment by drewdez** [comment]
What about adding a remote mode that would only allow two users to be in spymaster view at a time?
