### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by tna76874** [jbowens/codenames#146]
Hi there,

I don't know if it is me or some missing dependency, but the docker build fails with:

`/bin/sh: lscpu: not found`

Any ideas ?

Regards

**Comment by jbowens** [comment]
Sorry, I'm not sure. I don't use the Docker image personally.

**Comment by jrbarronumd** [comment]
It is still working for me, using docker-compose.  I'm no expert but I can try to weigh in if you can show how you're creating the image and running the container.

**Comment by j-zarp** [comment]
You need to install ```util-linux``` (this [alpine package](https://pkgs.alpinelinux.org/package/edge/main/x86_64/util-linux) includes a binary for lscpu).
Make the following change to your Dockerfile:
```
RUN apk add util-linux \
    && npm install -g parcel-bundler \
    && npm install \
    && sh build.sh
```

**Comment by tna76874** [comment]
Thank you for you answers. Unfortunately the building still fails. I append a full log of the building process of both modified and unmodified Dockerfile.
[docker.log](https://github.com/jbowens/codenames/files/6099438/docker.log)
[docker_mod.log](https://github.com/jbowens/codenames/files/6099440/docker_mod.log)

Thanks!

**Comment by j-zarp** [comment]
The new error that you get with the modified Dockerfile is related to the parcel-bundler package.
A fix is to explicitly specify the version of parcel-bundler in the Dockerfile:
```
npm install -g parcel-bundler@1.12.3
```
More details on this issue here: https://github.com/parcel-bundler/parcel/issues/5943

**Comment by tna76874** [comment]
@jdespraz thats it !
Build is working - I append the log and die Dockerfile.
[docker_mod2.log](https://github.com/jbowens/codenames/files/6099577/docker_mod2.log)

[Dockerfile.txt](https://github.com/jbowens/codenames/files/6099579/Dockerfile.txt)

Thanks!
