### ISSUE TITLE
Custom Words?

### ISSUE THREAD

**Issue by dnguyen722** [jbowens/codenames#15]
Hi Jackson, thanks for the wonderful app. It's very clean. Have you thought about adding a custom word list feature? This would help teachers like me immensely as we can use your app to review vocabulary with students.

**Comment by jbowens** [comment]
Hi @dnguyen722, good idea! I'll try and add this sometime soon

**Comment by Tyloendis** [comment]
Great idea! Would love to see this feature.
Any, ETA?

**Comment by jbowens** [comment]
@Tyloendis I'll try to implement it this week.

**Comment by jbowens** [comment]
@dnguyen722 @Tyloendis

Ok, now the [homepage](https://www.horsepaste.com/) has a dropdown from which you can edit the word list used for a game.

**Comment by Tyloendis** [comment]
Thanks!
