### ISSUE TITLE
Player data for scientific purposes

### ISSUE THREAD

**Issue by itsLuisa** [jbowens/codenames#150]
Hi there!

My name is Luisa and I am a student at Saarland University. I am currently writing my Bachelor thesis on semantic similarity in codenames. Therefore, I would like to ask you, whether there is any chance of you making collected player data available.
This would be a great help for my research!
Thanks in advance!

Best regards,
Luisa

**Comment by jbowens** [comment]
Sorry, the app does not collect any data and removes all record of games shortly after they are completed.
