### ISSUE TITLE
Custom Words - problem

### ISSUE THREAD

**Issue by Tyloendis** [jbowens/codenames#18]
Hello!
Thanks for this feature it works nice. Hovewer there is one problems, I don't know if this is intended or not, but after clicking on "next game" the new words are reverting to default ones.

https://gyazo.com/003aea793106ef098c6b6bddb1dee0b1

**Comment by jbowens** [comment]
Oops, good catch! Just fixed it.

**Comment by jbowens** [comment]
I noticed in your screen capture that there are some layout issues with longer words. Feel free to create an issue for that if it's a problem. I think there are a few options for scaling the font-size so that the text always fits.
