### ISSUE TITLE
Support for Duet/Deep Undercover Word Sets

### ISSUE THREAD

**Issue by Nathansbud** [jbowens/codenames#24]
I've been using codenames.plus recently, due to their support for the Duet/Deep Undercover wordsets, but I prefer the pared down login system of your version. Have you considered adding more the words from the expansions?

**Comment by jbowens** [comment]
Good idea. The UI needs a bit of work, but you can use custom word sets today by creating the game from the home page and pasting your own word set in the textarea. I'd like to fix up this UI and build those word sets into the game soon, but that workaround exists if you need it.

**Comment by Nathansbud** [comment]
Sounds good! Their repo has the word text files [here](https://github.com/Joooop/codenames.plus/tree/master/server) if you want them.
