### ISSUE TITLE
Words sometimes appear several times in consecutive games

### ISSUE THREAD

**Issue by dojitza** [jbowens/codenames#25]
Currently, the game takes random words from the word pool for each game. Once used, the word should be removed from the list so further games do not contain it. I suggest coupling a set (sets for multilingual support) of words to a game ID from which the game selects its words. On new game generation, the Game should pop the selected words from the set, and the server should ensure that the set contains at least 25 words for the game to take (reload the words from default word set). 

Some additional comments.

Memory issues: Since each game ID has it's own set of words and as far as I can see, you don't have any permanent storage (I guess this is by design), the sets need to be kept in the working memory. I believe you already have a separate word set for each game state so this should not be an issue.

User perception of the reducing word set: This implementation should ensure that the user plays at least 16 games before encountering a word again (assuming a single user/group uses the id).

**Comment by jmcshane** [comment]
With the game state object, could you store played words in an array on the game?

**Comment by jbowens** [comment]
> With the game state object, could you store played words in an array on the game?

You could, but the full word list is pretty sizable. I've dealt with a similar problem in previous projects, and one solution I kinda like is to store just a tuple of a pseudorandom generator seed and an index: (_s_, _i_).

When you want to determine the words for the next game, you seed a pseudorandom number generator with the stored seed _s_. Then you use the generator to generate a permutation, (eg. through the Go stdlib's [rand.Rand.Perm](https://golang.org/pkg/math/rand/#Rand.Perm) function). Next you take elements _i_ ... _i_+_n_  from the permutation to use as your game's words, updating the game state's index to _i_+_n_.

If you run off the end of the permutation, you create a new random seed for the pseudorandom generator and update the game state's seed.

---

This has issue been in the back of my mind for a while, but I just haven't had time to get to it. If anyone wants to take a stab at the approach I described above, feel free.

**Comment by jmcshane** [comment]
ok, so you store the seed and the index in the game state, regenerating seed as needed. makes sense (and much easier than trying to avoid collisions in a narrowing sample space)

Let me see what I can do while quarantined :)

**Comment by aboredman** [comment]
Haven't worked in Go before but it's as good a time as any to learn! I'll see what I can do also.
