### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by AstroCX1** [jbowens/codenames#42]
Seems the host is down. Perhaps there is too much traffic due to the stay at home sheltering.

**Comment by jbowens** [comment]
Hi @ajuni7,

Thanks for the note! It should be back up now. Yeah, the traffic growth over the past two weeks has been a lot. It turned out that the process hit its ulimit on open file descriptors, which was still the default 1024.

**Comment by AstroCX1** [comment]
@jbowens thanks for the quick response last this. This is really helping with the quarantine.

Looks like it’s happening again, maybe the limit wasn’t increased enough?
