### ISSUE TITLE
Filenodes exceeding cap, still open

### ISSUE THREAD

**Issue by AstroCX1** [jbowens/codenames#51]
@jbowens thanks for the quick response last this. This is really helping with the quarantine.

Looks like it’s happening again, maybe the limit wasn’t increased enough?

_Originally posted by @ajuni7 in https://github.com/jbowens/codenames/issues/42#issuecomment-605715262_

**Comment by jbowens** [comment]
Hi @ajuni7 — thanks again for dropping a note. I think this latest issue was caused by a deadlock in the code. I just deployed something that should fix that.

**Comment by AstroCX1** [comment]
You the best! Thanks again
