### ISSUE TITLE
Docker: go: directory /go/src/codenames outside available modules

### ISSUE THREAD

**Issue by Tadaboody** [jbowens/codenames#54]
I keep getting this error while building the docker:

```sh
 ---> Running in d04847700397
go: directory /go/src/codenames outside available modules
The command '/bin/sh -c go build /go/src/codenames &&     go build /app/cmd/codenames/main.go &&     cd /app/frontend/ &&     npm install &&     sh build.sh' returned a non-zero code: 1
```
But if I remove building `/go/src/codenames` completely it to build (and run!) just fine:
```diff
-RUN go build /go/src/codenames && \
-    go build /app/cmd/codenames/main.go && \
+RUN go build /app/cmd/codenames/main.go && \
     cd /app/frontend/ && \
     npm install && \
     sh build.sh
```

Could you explain why you try to build whats in your GOPATH? isn't just putting it there enough? why put it there at all?

Thank you for your time and your wonderful implementation!

**Comment by jbowens** [comment]
Sorry, someone from the community contributed the Dockerfile, and I don't use Docker. I might have broken the docker setup accidentally at some point.

Agree the double `go build` looks unnecessary.
