### ISSUE TITLE
Customizable word lists

### ISSUE THREAD

**Issue by bernZ** [jbowens/codenames#59]
Feature Request

I noticed that basically the game has a 400 word list baked into it (at least for English!). It'd be great if custom word lists support was made available. It gives a lot more options for gameplay (our friends played several rounds and quickly found words repeating themselves). It'd also give more mechanisms to do things like custom lists, or domain specific words if you were playing with a particular community.

**Comment by jbowens** [comment]
Hi @bernZ,

If you create the game from the homepage and click on a language's label to expand it, you can add custom word lists:

![Screen Shot 2020-04-02 at 3 17 56 PM](https://user-images.githubusercontent.com/867352/78292692-71023100-74f5-11ea-8159-abdbfd57850e.png)

**Comment by jbowens** [comment]
The UI here does need some work to make it more discoverable.

**Comment by bernZ** [comment]
Good enough for now, will take advantage of this! But I agree, something in the UI to make this more discoverable is probably ideal.  User error here, closing this :)
