### ISSUE TITLE
more playeres with larger grid

### ISSUE THREAD

**Issue by goatey32** [jbowens/codenames#65]
Increase the number of players/boxes for twice the number of players

**Comment by jbowens** [comment]
Sorry, I don't understand? I think the 5x5 grid scales well to large number of players in a game.

**Comment by goatey32** [comment]
So we played with 4 of us and it worked out well. But we think more players
would be fu . So with 10 people for example you would have 5 teams of 2,
and it would add another confounding variable.

You would need a larger grid and some additional colors for teams.

Does this make sense?
Best

Gehry

**Comment by Pumpido75** [comment]
Just play it with to teams - no matter how many players in every team!
That's the fun of the game!

**Comment by goatey32** [comment]
Ok. We will try. Like that idea.
Fun game! Thanks

**Comment by CWempe** [comment]
This would be great improvement.

I have not played it with 10+ people, yet.
But I think it would be hard to discuss your guesses with 5+ people at the same time over a video call.

I vote for reopening this issue.
Even it will not be implemented any time soon.
