### ISSUE TITLE
Intermittent board resets on www.horsepaste.com

### ISSUE THREAD

**Issue by kavun** [jbowens/codenames#7]
Me and my friends have loved this. We've played over 30 games over the last 3 months.

About 3 or 4 times in those 30 games the board has completely reset. Haven't found a cause yet, but wanted to see if you were aware of this, or have any idea why it might be happening.

**Comment by kavun** [comment]
I see that unfinished games are removed after 24 hours.

https://github.com/jbowens/codenames/blob/e955111c8463d7f6c3ecfdd197152728b4e8664b/server.go#L132

We'll try to finish games faster from now on!

**Comment by jbowens** [comment]
Ah, sorry about that! I mostly intended the app for playing in-person games, so I didn't expect games to be needed for more than 24 hours. Also, all game state is held in-memory so a deploy of a new version will also wipe all existing games out.

**Comment by LukeGoodsell** [comment]
Hi, thanks for creating horsepaste.com! I'd been trying to play a game with my family via email and just fell victim to the 24 hour limit; it might be nice to have a note on the front page that games must complete within 24 hours in case there are any others trying to do the same.
